In [1]:
import numpy as np

In [4]:
def sigmoide(x):
    return 1.0/(1.0 + np.exp(-x))

def sigmoideDerivada(x):
    return x*(1.0 - x)

class PerceptronDidatico:
    def __init__(self, entradas):
        self.entradas = entradas
        self.TamEntrada =len(self.entradas)
        self.TamCadaEntrada = len(self.entradas[0])

        self.pesosI = np.random.random((self.TamCadaEntrada, self.TamEntrada)) # 2  4
        self.pesosH = np.random.random((self.TamEntrada, 1))  #  4   1

    def sinal(self, inp):
        print('Entrada:')
        print(inp)
        
        print('\nPesosI:')
        print(self.pesosI)
        
        s1 = sigmoide(np.dot(inp, self.pesosI))
        
        print('\nEntrada X PesosI: ')
        print(np.dot(inp, self.pesosI))
        
        print('\nSigmoide(Entrada X PesosI):')
        print(s1)
        
        s2 = sigmoide(np.dot(s1, self.pesosH))
        
        print('\nCamada1')
        print(s1)
        
        print('\n______________________________________________________________\n')
        
        print('\nCamada1')
        print(s1)
        
        print('\nPesosH')
        print(self.pesosH)
        
        print('\nCamada1 X PesosH')
        print(np.dot(s1, self.pesosH))
        
        print('\nSigmoide(Camada1XPesosH)')
        print(s2)
       
        print('\n______________________________________________________________\n')
        
        print('Retorna Camada2')
        print(s2)
        return s2

    def treino(self, entradas, saidas, nroIteracoes):
        for i in range(nroIteracoes):
            camada0 = entradas
            camada1 = sigmoide(np.dot(camada0, self.pesosI)) # multiplicando matrizes e aplicando sigmoide
            camada2 = sigmoide(np.dot(camada1, self.pesosH))
            
  
            
            print('\nSaída Desejada:')
            print(saidas)
            
            print('\nSaída:')
            print(camada2)
            
            camada2Erro = saidas - camada2
            
            print('\nErro (Desejada - Saída):')
            print(camada2Erro)
            
            print('\n______________________________________________________________\n')

            camada2Delta = np.multiply(camada2Erro, sigmoideDerivada(camada2)) # gradiente
            print('\nCamada2: ')
            print(camada2)
            
            print('\nDerivadaSigmoide(Camada2): ')
            print(sigmoideDerivada(camada2))
            
            print('\nErro * DerivadaSigmoide(Camada2): (Camada2Delta)')
            print(camada2Delta)
            
            print('\nPesosH Transposto')
            print(self.pesosH.T)
            
            camada1Erro = np.dot(camada2Delta, self.pesosH.T)
            print('\(Erro * DerivadaSigmoide(Camada2)) X PesosH Transposto: (ErroCamada1)')
            print(np.dot(camada2Delta, self.pesosH.T))
             
            print('\nCamada1')
            print(camada1)
            
            print('\nDerivadaSigmoide(Camada1)')
            print(sigmoideDerivada(camada1))
            
            camada1Delta = np.multiply(camada1Erro, sigmoideDerivada(camada1))
            print('\nErroCamada1 X DerivadaSigmoide(Camada1)')
            print(camada1Delta)
            
            print('\n______________________________________________________________\n')
            
            print('\nPesosH Antigo: ')
            print(self.pesosH)
            self.pesosH += np.dot(camada1.T, camada2Delta)
            print('\nPesosH Novo: ')
            print(self.pesosH)
            
            print('\nPesosI Antigo: ')
            print(self.pesosI)   
            self.pesosI += np.dot(camada0.T, camada1Delta)
            print('\nPesosI Novo: ')
            print(self.pesosI)

In [9]:
entradas=np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
saidas=np.array([[0], [1], [1], [0]])

n = PerceptronDidatico(entradas)
n.treino(entradas, saidas, 1)


Saída Desejada:
[[0]
 [1]
 [1]
 [0]]

Saída:
[[0.7224075 ]
 [0.76734167]
 [0.74775207]
 [0.78771253]]

Erro (Desejada - Saída):
[[-0.7224075 ]
 [ 0.23265833]
 [ 0.25224793]
 [-0.78771253]]

______________________________________________________________


Camada2: 
[[0.7224075 ]
 [0.76734167]
 [0.74775207]
 [0.78771253]]

DerivadaSigmoide(Camada2): 
[[0.2005349 ]
 [0.17852843]
 [0.18861891]
 [0.1672215 ]]

Erro * DerivadaSigmoide(Camada2): (Camada2Delta)
[[-0.14486792]
 [ 0.04153613]
 [ 0.04757873]
 [-0.13172247]]

PesosH Transposto
[[0.81515209 0.0055498  0.54277116 0.54939731]]
\(Erro * DerivadaSigmoide(Camada2)) X PesosH Transposto: (ErroCamada1)
[[-0.11808939 -0.00080399 -0.07863013 -0.07959005]
 [ 0.03385826  0.00023052  0.02254461  0.02281984]
 [ 0.0387839   0.00026405  0.02582436  0.02613963]
 [-0.10737385 -0.00073103 -0.07149516 -0.07236797]]

Camada1
[[0.5        0.5        0.5        0.5       ]
 [0.58985453 0.54205056 0.68213409 0.6175659 ]
 [0.61012677 0.59987378 0.56290994

In [12]:
n.sinal(np.array([0, 1]))

Entrada:
[0 1]

PesosI:
[[0.43420064 0.40483407 0.24538549 0.03151266]
 [0.34868518 0.16848922 0.75453614 0.4677018 ]]

Entrada X PesosI: 
[0.34868518 0.16848922 0.75453614 0.4677018 ]

Sigmoide(Entrada X PesosI):
[0.5862987  0.54202294 0.6801663  0.61483966]

Camada1
[0.5862987  0.54202294 0.6801663  0.61483966]

______________________________________________________________


Camada1
[0.5862987  0.54202294 0.6801663  0.61483966]

PesosH
[[ 0.70504715]
 [-0.10007525]
 [ 0.42872844]
 [ 0.44425813]]

Camada1 X PesosH
[0.9238793]

Sigmoide(Camada1XPesosH)
[0.71583188]

______________________________________________________________

Retorna Camada2
[0.71583188]


array([0.71583188])